// Bancos de dados sem repetições. Exatamente 25 perguntas por área.
// Cada módulo terá as suas 25 específicas + 25 gerais = 50 perguntas ÚNICAS reais.

const qGerais = [
    { id: 1, difficulty: 'facil', text: 'O Censo 2024 em Angola visa primariamente:', type: 'single', options: [{id:'a',text:'Aumentar impostos'}, {id:'b',text:'Contagem populacional para planear serviços'}, {id:'c',text:'Fecho de fronteiras'}], correctAnswers: ['b'] },
    { id: 2, difficulty: 'facil', text: 'Na Ética Profissional, o sigilo médico significa:', type: 'single', options: [{id:'a',text:'Não falar com o paciente'}, {id:'b',text:'Manter a privacidade dos dados do paciente'}, {id:'c',text:'Esconder erros médicos'}], correctAnswers: ['b'] },
    { id: 3, difficulty: 'facil', text: 'A Inteligência Artificial no diagnóstico médico serve para:', type: 'single', options: [{id:'a',text:'Substituir os médicos'}, {id:'b',text:'Auxiliar na identificação de padrões e doenças'}, {id:'c',text:'Proibir o uso de exames'}], correctAnswers: ['b'] },
    { id: 4, difficulty: 'facil', text: 'A probidade na função pública implica atuar com:', type: 'single', options: [{id:'a',text:'Desonestidade'}, {id:'b',text:'Retidão, honestidade e integridade'}, {id:'c',text:'Arrogância'}], correctAnswers: ['b'] },
    { id: 5, difficulty: 'facil', text: 'O Inquérito de Indicadores Múltiplos e de Saúde (IIMS) mede:', type: 'single', options: [{id:'a',text:'Mortalidade e nutrição'}, {id:'b',text:'Apenas produção agrícola'}, {id:'c',text:'Tráfego automóvel'}], correctAnswers: ['a'] },
    { id: 6, difficulty: 'normal', text: 'A Nova Divisão Político-Administrativa de Angola (2024) tem impacto na saúde porque:', type: 'single', options: [{id:'a',text:'Descentraliza a gestão hospitalar e aproxima os serviços'}, {id:'b',text:'Obriga todos a irem a Luanda'}, {id:'c',text:'Reduz o número de municípios'}], correctAnswers: ['a'] },
    { id: 7, difficulty: 'normal', text: 'Um dos deveres do funcionário público é a assiduidade, que significa:', type: 'single', options: [{id:'a',text:'Faltar justificadamente'}, {id:'b',text:'Comparecer regular e pontualmente ao serviço'}, {id:'c',text:'Trabalhar por turnos'}], correctAnswers: ['b'] },
    { id: 8, difficulty: 'normal', text: 'No contexto de bioética, o Princípio da Autonomia determina que:', type: 'single', options: [{id:'a',text:'O médico decide sozinho'}, {id:'b',text:'O paciente capaz tem o direito de aceitar ou recusar tratamentos'}, {id:'c',text:'O hospital não tem regras'}], correctAnswers: ['b'] },
    { id: 9, difficulty: 'normal', text: 'A utilização do Big Data na Saúde Pública permite:', type: 'single', options: [{id:'a',text:'Identificar rapidamente surtos e tendências epidemiológicas'}, {id:'b',text:'Apagar processos antigos'}, {id:'c',text:'Reduzir o tamanho dos hospitais'}], correctAnswers: ['a'] },
    { id: 10, difficulty: 'normal', text: 'Um fator que influencia diretamente a Taxa de Mortalidade Infantil (medida pelo IIMS) é:', type: 'multiple', options: [{id:'a',text:'Nutrição e acesso a vacinas'}, {id:'b',text:'Acesso a estradas betuminosas'}, {id:'c',text:'Saneamento básico e água potável'}], correctAnswers: ['a','c'] },
    { id: 11, difficulty: 'dificil', text: 'Em termos legais, a recusa de prestação de socorro urgente pelo técnico de saúde é considerada:', type: 'single', options: [{id:'a',text:'Um direito sindical'}, {id:'b',text:'Omissão de socorro, punível civil e criminalmente'}, {id:'c',text:'Falta leve'}], correctAnswers: ['b'] },
    { id: 12, difficulty: 'dificil', text: 'Qual o risco ético do uso de algoritmos preditivos (IA) na triagem de emergências?', type: 'single', options: [{id:'a',text:'A rapidez excessiva'}, {id:'b',text:'Viés algorítmico que pode discriminar grupos minoritários'}, {id:'c',text:'Gasto de muita eletricidade'}], correctAnswers: ['b'] },
    { id: 13, difficulty: 'dificil', text: 'O conceito de Desconcentração Administrativa (presente na Nova Divisão) difere da Descentralização por:', type: 'single', options: [{id:'a',text:'Ser a mesma coisa'}, {id:'b',text:'Na desconcentração mantém-se a subordinação hierárquica à entidade central'}, {id:'c',text:'A descentralização não permite orçamentos'}], correctAnswers: ['b'] },
    { id: 14, difficulty: 'dificil', text: 'De acordo com o PAV (Programa Alargado de Vacinação), a prevenção de Pólio e Tuberculose faz-se com:', type: 'single', options: [{id:'a',text:'VOP e BCG respetivamente'}, {id:'b',text:'Pentavalente apenas'}, {id:'c',text:'Rotavírus e Febre Amarela'}], correctAnswers: ['a'] },
    { id: 15, difficulty: 'dificil', text: 'A recolha de dados sensíveis num Censo respeita o Princípio do Segredo Estatístico, o que implica:', type: 'single', options: [{id:'a',text:'Publicar os nomes dos infetados'}, {id:'b',text:'Os dados não podem ser usados para fiscalização ou processos judiciais individuais'}, {id:'c',text:'Os dados são eliminados no dia seguinte'}], correctAnswers: ['b'] },
    { id: 16, difficulty: 'facil', text: 'Um funcionário que trata os utentes com má educação viola o dever de:', type: 'single', options: [{id:'a',text:'Urbanidade'}, {id:'b',text:'Assiduidade'}, {id:'c',text:'Sigilo'}], correctAnswers: ['a'] },
    { id: 17, difficulty: 'normal', text: 'O Inquérito IIMS é fundamental para avaliar o cumprimento dos:', type: 'single', options: [{id:'a',text:'Objetivos de Desenvolvimento Sustentável (ODS)'}, {id:'b',text:'Critérios do Banco Central'}, {id:'c',text:'Plano de Transportes'}], correctAnswers: ['a'] },
    { id: 18, difficulty: 'dificil', text: 'Em bioética, o Princípio da Justiça distributiva obriga o sistema de saúde a:', type: 'single', options: [{id:'a',text:'Dar mais aos mais ricos'}, {id:'b',text:'Garantir acesso equitativo aos cuidados, minimizando desigualdades'}, {id:'c',text:'Aplicar penas de prisão'}], correctAnswers: ['b'] },
    { id: 19, difficulty: 'normal', text: 'O uso de IA na farmácia hospitalar pode otimizar:', type: 'single', options: [{id:'a',text:'A prescrição aleatória'}, {id:'b',text:'A previsão de roturas de stock e prazos de validade'}, {id:'c',text:'A destruição de medicamentos'}], correctAnswers: ['b'] },
    { id: 20, difficulty: 'facil', text: 'O Ministério da Saúde (MINSA) de Angola foca-se na prevenção através de:', type: 'single', options: [{id:'a',text:'Campanhas de vacinação e saneamento'}, {id:'b',text:'Venda de carros'}, {id:'c',text:'Construção civil exclusiva'}], correctAnswers: ['a'] },
    { id: 21, difficulty: 'normal', text: 'Em relação aos direitos do doente, o "Consentimento Informado" consiste em:', type: 'single', options: [{id:'a',text:'Omitir os riscos da cirurgia'}, {id:'b',text:'Fornecer informação clara para que o doente autorize ou recuse a intervenção'}, {id:'c',text:'Cobrar antecipadamente'}], correctAnswers: ['b'] },
    { id: 22, difficulty: 'dificil', text: 'Um indicador clássico de saúde pública relacionado com saneamento precário e verificado pelo IIMS é:', type: 'single', options: [{id:'a',text:'Taxa de obesidade adulta'}, {id:'b',text:'Prevalência de doenças diarreicas agudas em menores de 5 anos'}, {id:'c',text:'Acidentes de viação'}], correctAnswers: ['b'] },
    { id: 23, difficulty: 'normal', text: 'O Princípio da Não-Maleficência dita que o profissional deve:', type: 'single', options: [{id:'a',text:'Causar o menor dano possível ao paciente'}, {id:'b',text:'Receitar tratamentos dolorosos sem motivo'}, {id:'c',text:'Ignorar as dores'}], correctAnswers: ['a'] },
    { id: 24, difficulty: 'facil', text: 'O comportamento do funcionário público rege-se por qual destes diplomas legais?', type: 'single', options: [{id:'a',text:'Código Comercial'}, {id:'b',text:'Pauta Deontológica do Serviço Público e Lei de Bases da Função Pública'}, {id:'c',text:'Lei de Estradas'}], correctAnswers: ['b'] },
    { id: 25, difficulty: 'dificil', text: 'Uma das utilidades demográficas do Censo para a Terapêutica Superior é:', type: 'single', options: [{id:'a',text:'Ajustar o cálculo epidemiológico para a incidência de doenças negligenciadas em certas províncias'}, {id:'b',text:'Recusar tratamento a estrangeiros'}, {id:'c',text:'Extinguir unidades de fisioterapia'}], correctAnswers: ['a'] }
];

const qAnalises = [
    { id: 101, difficulty: 'facil', text: 'Os eritrócitos são responsáveis pelo transporte de:', type: 'single', options: [{id:'a',text:'Bactérias'}, {id:'b',text:'Oxigénio'}, {id:'c',text:'Plaquetas'}], correctAnswers: ['b'] },
    { id: 102, difficulty: 'facil', text: 'O Leucograma avalia os:', type: 'single', options: [{id:'a',text:'Glóbulos Brancos'}, {id:'b',text:'Glóbulos Vermelhos'}, {id:'c',text:'Lípidos'}], correctAnswers: ['a'] },
    { id: 103, difficulty: 'normal', text: 'Uma Eosinofilia (aumento de eosinófilos) pode ser indicativa de:', type: 'single', options: [{id:'a',text:'Parasitose intestinal'}, {id:'b',text:'Fratura óssea'}, {id:'c',text:'Diabetes'}], correctAnswers: ['a'] },
    { id: 104, difficulty: 'normal', text: 'A Coloração de Gram divide as bactérias em Positivas e Negativas com base na:', type: 'single', options: [{id:'a',text:'Espessura do flagelo'}, {id:'b',text:'Estrutura e espessura da parede celular (peptidoglicano)'}, {id:'c',text:'Cápsula viral'}], correctAnswers: ['b'] },
    { id: 105, difficulty: 'dificil', text: 'A prova da Coagulase distingue o Staphylococcus aureus (positivo) do:', type: 'single', options: [{id:'a',text:'Streptococcus pyogenes'}, {id:'b',text:'Staphylococcus epidermidis (negativo)'}, {id:'c',text:'Escherichia coli'}], correctAnswers: ['b'] },
    { id: 106, difficulty: 'dificil', text: 'Em hematologia, a Drepanocitose é causada por uma mutação genética que produz:', type: 'single', options: [{id:'a',text:'Hemoglobina F'}, {id:'b',text:'Hemoglobina S (HbS)'}, {id:'c',text:'Metahemoglobina'}], correctAnswers: ['b'] },
    { id: 107, difficulty: 'facil', text: 'O Antibiograma serve para:', type: 'single', options: [{id:'a',text:'Medir o oxigénio'}, {id:'b',text:'Avaliar a sensibilidade/resistência bacteriana a antibióticos'}, {id:'c',text:'Ver o tipo de sangue'}], correctAnswers: ['b'] },
    { id: 108, difficulty: 'normal', text: 'A presença abundante de glicose no exame químico da urina chama-se:', type: 'single', options: [{id:'a',text:'Proteinúria'}, {id:'b',text:'Glicosúria'}, {id:'c',text:'Hematúria'}], correctAnswers: ['b'] },
    { id: 109, difficulty: 'normal', text: 'A técnica de Ziehl-Neelsen foca-se na identificação de BAAR, o que inclui:', type: 'single', options: [{id:'a',text:'Vírus HIV'}, {id:'b',text:'Micobactéria da Tuberculose'}, {id:'c',text:'Fungos superficiais'}], correctAnswers: ['b'] },
    { id: 110, difficulty: 'dificil', text: 'O Ágar MacConkey é um meio de cultura:', type: 'single', options: [{id:'a',text:'Seletivo e Diferencial para bacilos Gram-negativos e fermentação da lactose'}, {id:'b',text:'Exclusivo para fungos'}, {id:'c',text:'Apenas nutritivo básico'}], correctAnswers: ['a'] },
    { id: 111, difficulty: 'normal', text: 'Qual destas é uma micose sistémica oportunista comum em imunocomprometidos?', type: 'single', options: [{id:'a',text:'Candidíase e Aspergilose'}, {id:'b',text:'Dermatofitose'}, {id:'c',text:'Pitiríase versicolor'}], correctAnswers: ['a'] },
    { id: 112, difficulty: 'facil', text: 'No laboratório, a esterilização por Autoclave usa:', type: 'single', options: [{id:'a',text:'Álcool absoluto'}, {id:'b',text:'Calor húmido e alta pressão'}, {id:'c',text:'Radiação gama'}], correctAnswers: ['b'] },
    { id: 113, difficulty: 'dificil', text: 'Na Coproparasitologia, a pesquisa de ovos pesados de helmintos (ex: Schistosoma) requer frequentemente técnicas de:', type: 'single', options: [{id:'a',text:'Coloração de Giemsa exclusiva'}, {id:'b',text:'Concentração por sedimentação'}, {id:'c',text:'Gota Espessa'}], correctAnswers: ['b'] },
    { id: 114, difficulty: 'normal', text: 'A causa principal de Anemia Microcítica Hipocrómica é geralmente:', type: 'single', options: [{id:'a',text:'Falta de Vitamina B12'}, {id:'b',text:'Deficiência de Ferro (Ferropénica)'}, {id:'c',text:'Aplasia Medular'}], correctAnswers: ['b'] },
    { id: 115, difficulty: 'facil', text: 'O parasita causador da Malária pertence ao género:', type: 'single', options: [{id:'a',text:'Ascaris'}, {id:'b',text:'Plasmodium'}, {id:'c',text:'Trypanosoma'}], correctAnswers: ['b'] },
    { id: 116, difficulty: 'normal', text: 'Em parasitologia, a técnica de Gota Espessa é usada primariamente para diagnosticar:', type: 'single', options: [{id:'a',text:'Infeções urinárias'}, {id:'b',text:'Malária e outros hematozoários'}, {id:'c',text:'Hepatite B'}], correctAnswers: ['b'] },
    { id: 117, difficulty: 'dificil', text: 'A prova do CAMP é útil na identificação de qual grupo bacteriano?', type: 'single', options: [{id:'a',text:'Estafilococos coagulase negativos'}, {id:'b',text:'Streptococcus agalactiae (Grupo B)'}, {id:'c',text:'Enterococcus faecalis'}], correctAnswers: ['b'] },
    { id: 118, difficulty: 'normal', text: 'O exame VDRL é uma prova serológica fundamental no diagnóstico de:', type: 'single', options: [{id:'a',text:'Sida'}, {id:'b',text:'Sífilis'}, {id:'c',text:'Tuberculose'}], correctAnswers: ['b'] },
    { id: 119, difficulty: 'facil', text: 'O tubo de colheita de sangue com tampa roxa (EDTA) é usado para:', type: 'single', options: [{id:'a',text:'Bioquímica'}, {id:'b',text:'Hemograma completo'}, {id:'c',text:'Coagulação'}], correctAnswers: ['b'] },
    { id: 120, difficulty: 'dificil', text: 'Um fator pré-analítico severo que eleva a taxa de potássio numa amostra é:', type: 'single', options: [{id:'a',text:'A Hemólise durante a colheita'}, {id:'b',text:'A centrifugação correta'}, {id:'c',text:'A refrigeração a 4ºC'}], correctAnswers: ['a'] },
    { id: 121, difficulty: 'normal', text: 'As reações de Hemaglutinação são utilizadas no laboratório para determinar:', type: 'single', options: [{id:'a',text:'Grupos sanguíneos'}, {id:'b',text:'Taxa de glicose'}, {id:'c',text:'Colesterol'}], correctAnswers: ['a'] },
    { id: 122, difficulty: 'facil', text: 'Plaquetas baixas (trombocitopenia) geram risco de:', type: 'single', options: [{id:'a',text:'Hemorragias espontâneas'}, {id:'b',text:'Asfixia'}, {id:'c',text:'Insuficiência renal'}], correctAnswers: ['a'] },
    { id: 123, difficulty: 'dificil', text: 'A presença de Cilindros Hialinos num sedimento urinário indica:', type: 'single', options: [{id:'a',text:'Sempre insuficiência renal terminal'}, {id:'b',text:'Geralmente um quadro benigno ou desidratação, resultando de proteínas precipitadas'}, {id:'c',text:'Infeção bacteriana severa'}], correctAnswers: ['b'] },
    { id: 124, difficulty: 'normal', text: 'A Troponina e a CK-MB são enzimas utilizadas no diagnóstico de:', type: 'single', options: [{id:'a',text:'Enfarte Agudo do Miocárdio'}, {id:'b',text:'Hepatite'}, {id:'c',text:'Pneumonia'}], correctAnswers: ['a'] },
    { id: 125, difficulty: 'dificil', text: 'Qual o reagente diferencial primário usado na coloração de Gram?', type: 'single', options: [{id:'a',text:'Álcool-Cetona (Descolorante)'}, {id:'b',text:'Cristal Violeta'}, {id:'c',text:'Fucsina'}], correctAnswers: ['a'] }
];

const qFarmacia = [
    { id: 201, difficulty: 'facil', text: 'Qual das seguintes vias é uma "Via Enteral"?', type: 'single', options: [{id:'a',text:'Intravenosa'}, {id:'b',text:'Oral'}, {id:'c',text:'Subcutânea'}], correctAnswers: ['b'] },
    { id: 202, difficulty: 'facil', text: 'A Farmacocinética estuda os processos que o medicamento sofre no corpo, nomeadamente:', type: 'single', options: [{id:'a',text:'Preço e comercialização'}, {id:'b',text:'Absorção, Distribuição, Biotransformação e Excreção'}, {id:'c',text:'O design da embalagem'}], correctAnswers: ['b'] },
    { id: 203, difficulty: 'normal', text: 'A biodisponibilidade de um fármaco administrado por via intravenosa é:', type: 'single', options: [{id:'a',text:'50%'}, {id:'b',text:'100%'}, {id:'c',text:'Variável consoante o fígado'}], correctAnswers: ['b'] },
    { id: 204, difficulty: 'normal', text: 'O órgão primariamente responsável pela biotransformação (metabolismo) dos fármacos é:', type: 'single', options: [{id:'a',text:'O coração'}, {id:'b',text:'O fígado'}, {id:'c',text:'Os pulmões'}], correctAnswers: ['b'] },
    { id: 205, difficulty: 'dificil', text: 'O Efeito de Primeira Passagem ocorre frequentemente em qual via de administração?', type: 'single', options: [{id:'a',text:'Sublingual'}, {id:'b',text:'Oral (passagem pelo sistema porta-hepático)'}, {id:'c',text:'Intravenosa'}], correctAnswers: ['b'] },
    { id: 206, difficulty: 'facil', text: 'A Farmacodinâmica estuda essencialmente:', type: 'single', options: [{id:'a',text:'A eliminação da droga'}, {id:'b',text:'O que a droga faz ao corpo (Ação, Efeito e Mecanismo)'}, {id:'c',text:'O peso do comprimido'}], correctAnswers: ['b'] },
    { id: 207, difficulty: 'normal', text: 'Na gestão de estoques, o sistema FEFO (First Expire, First Out) assegura que:', type: 'single', options: [{id:'a',text:'Os medicamentos mais caros saem primeiro'}, {id:'b',text:'Os medicamentos que expiram mais cedo são dispensados primeiro'}, {id:'c',text:'Os antibióticos têm prioridade'}], correctAnswers: ['b'] },
    { id: 208, difficulty: 'dificil', text: 'A Classificação ABC no stock da farmácia hospitalar visa controlar:', type: 'single', options: [{id:'a',text:'Custo e volume de capital investido (onde A = Alto valor/baixo volume)'}, {id:'b',text:'Ordem alfabética de paracetamol a zolpidem'}, {id:'c',text:'Grupos sanguíneos dos pacientes'}], correctAnswers: ['a'] },
    { id: 209, difficulty: 'normal', text: 'As cápsulas e os comprimidos revestidos enquadram-se na forma farmacêutica:', type: 'single', options: [{id:'a',text:'Semissólida'}, {id:'b',text:'Sólida'}, {id:'c',text:'Gasosa'}], correctAnswers: ['b'] },
    { id: 210, difficulty: 'facil', text: 'Um efeito adverso medicamentoso é definido como:', type: 'single', options: [{id:'a',text:'A cura instantânea da patologia'}, {id:'b',text:'Uma reação nociva e não intencional ao uso da droga'}, {id:'c',text:'A absorção rápida da água'}], correctAnswers: ['b'] },
    { id: 211, difficulty: 'dificil', text: 'Antagonismo Farmacológico Competitivo ocorre quando:', type: 'single', options: [{id:'a',text:'Dois fármacos agem em locais distintos do corpo'}, {id:'b',text:'Dois fármacos disputam o mesmo receptor celular (ex: Naloxona e Opiáceos)'}, {id:'c',text:'A absorção é anulada no estômago'}], correctAnswers: ['b'] },
    { id: 212, difficulty: 'normal', text: 'O Racional do Uso de Medicamentos implica:', type: 'multiple', options: [{id:'a',text:'Prescrever o fármaco adequado às necessidades clínicas'}, {id:'b',text:'Dar doses superiores ao limite'}, {id:'c',text:'Administrar com menor custo possível para o utente/Estado'}], correctAnswers: ['a','c'] },
    { id: 213, difficulty: 'facil', text: 'Os Antibióticos são usados exclusivamente para tratar:', type: 'single', options: [{id:'a',text:'Infeções Virais (Gripe)'}, {id:'b',text:'Infeções Bacterianas'}, {id:'c',text:'Tromboses'}], correctAnswers: ['b'] },
    { id: 214, difficulty: 'dificil', text: 'A Diluição de Soluções a partir de Concentrações baseia-se na fórmula matemática:', type: 'single', options: [{id:'a',text:'E = mc^2'}, {id:'b',text:'C1 x V1 = C2 x V2'}, {id:'c',text:'V = R x I'}], correctAnswers: ['b'] },
    { id: 215, difficulty: 'normal', text: 'Em Farmacovigilância, a notificação de reações adversas graves (RAM) serve para:', type: 'single', options: [{id:'a',text:'Retirar imediatamente do mercado todas as marcas'}, {id:'b',text:'Avaliar, monitorizar e prevenir riscos associados ao fármaco'}, {id:'c',text:'Cobrar mais caro'}], correctAnswers: ['b'] },
    { id: 216, difficulty: 'facil', text: 'Na via sublingual, o comprimido é colocado:', type: 'single', options: [{id:'a',text:'Debaixo da língua'}, {id:'b',text:'Na pele'}, {id:'c',text:'Nos olhos'}], correctAnswers: ['a'] },
    { id: 217, difficulty: 'normal', text: 'Uma das principais vantagens da via intravenosa é:', type: 'single', options: [{id:'a',text:'A fácil autoadministração em casa'}, {id:'b',text:'O efeito terapêutico imediato e previsível em urgências'}, {id:'c',text:'Poder ser revertida rapidamente através do vómito'}], correctAnswers: ['b'] },
    { id: 218, difficulty: 'dificil', text: 'O conceito de "Meia-Vida" (T1/2) biológica de um fármaco indica:', type: 'single', options: [{id:'a',text:'O tempo que demora a atingir 100% de concentração na urina'}, {id:'b',text:'O tempo necessário para que a concentração plasmática do fármaco caia para metade'}, {id:'c',text:'A data limite do medicamento antes de expirar'}], correctAnswers: ['b'] },
    { id: 219, difficulty: 'normal', text: 'A interação medicamentosa do tipo Sinergismo de Potenciação significa que:', type: 'single', options: [{id:'a',text:'O efeito final é menor que a soma das partes'}, {id:'b',text:'O efeito final é superior à simples soma algébrica dos efeitos individuais'}, {id:'c',text:'Um fármaco anula o outro'}], correctAnswers: ['b'] },
    { id: 220, difficulty: 'dificil', text: 'No cálculo de Gotejamento para macrogotas, a fórmula padrão é:', type: 'single', options: [{id:'a',text:'Volume (mL) / (Tempo (h) x 3)'}, {id:'b',text:'Volume (mL) x 60'}, {id:'c',text:'Dose / Peso Corporal'}], correctAnswers: ['a'] },
    { id: 221, difficulty: 'facil', text: 'A prescrição médica (receita) deve sempre conter de forma clara:', type: 'multiple', options: [{id:'a',text:'Nome e dosagem do medicamento'}, {id:'b',text:'Assinatura do médico e via de administração'}, {id:'c',text:'O partido político do paciente'}], correctAnswers: ['a','b'] },
    { id: 222, difficulty: 'normal', text: 'A profilaxia de infeções bacterianas hospitalares realiza-se fundamentalmente com base em:', type: 'single', options: [{id:'a',text:'Uso excessivo de antibióticos de largo espectro'}, {id:'b',text:'Protocolos rigorosos de higiene, lavagem das mãos e uso racional de antimicrobianos'}, {id:'c',text:'Vacinação oral contra o tétano'}], correctAnswers: ['b'] },
    { id: 223, difficulty: 'dificil', text: 'A depuração (Clearance) renal de um fármaco diminui drasticamente em doentes com:', type: 'single', options: [{id:'a',text:'Diabetes bem controlada'}, {id:'b',text:'Insuficiência Renal Crónica (TFG reduzida)'}, {id:'c',text:'Asma brônquica'}], correctAnswers: ['b'] },
    { id: 224, difficulty: 'normal', text: 'Em doentes asmáticos, a terapêutica broncodilatadora urgente é geralmente administrada por via:', type: 'single', options: [{id:'a',text:'Dérmica (pomadas)'}, {id:'b',text:'Inalatória (Aerossóis)'}, {id:'c',text:'Subcutânea profunda'}], correctAnswers: ['b'] },
    { id: 225, difficulty: 'facil', text: 'A Comissão de Farmácia e Terapêutica (CFT) do hospital é responsável por:', type: 'single', options: [{id:'a',text:'Limpar as prateleiras da farmácia'}, {id:'b',text:'Avaliar as práticas clínicas, selecionar os fármacos e garantir o seu uso seguro'}, {id:'c',text:'Produzir vacinas do zero'}], correctAnswers: ['b'] }
];

const qRadiologia = [
    { id: 301, difficulty: 'facil', text: 'A radiografia convencional baseia-se no uso de qual tipo de radiação?', type: 'single', options: [{id:'a',text:'Radiação X (Eletromagnética)'}, {id:'b',text:'Radiação Alfa'}, {id:'c',text:'Som de alta frequência'}], correctAnswers: ['a'] },
    { id: 302, difficulty: 'facil', text: 'O osso aparece na imagem radiográfica convencional com uma coloração:', type: 'single', options: [{id:'a',text:'Radiotransparente (Preta)'}, {id:'b',text:'Radiopaca (Branca)'}, {id:'c',text:'Cinzenta escura'}], correctAnswers: ['b'] },
    { id: 303, difficulty: 'normal', text: 'Os 3 princípios básicos da Proteção Radiológica contra radiações ionizantes são:', type: 'single', options: [{id:'a',text:'Lavagem de mãos, Esterilização e Quarentena'}, {id:'b',text:'Tempo (menor), Distância (maior) e Blindagem (chumbo)'}, {id:'c',text:'Velocidade, Força e Direção'}], correctAnswers: ['b'] },
    { id: 304, difficulty: 'normal', text: 'O uso de contrastes radiológicos com base em Sulfato de Bário é indicado para exames de:', type: 'single', options: [{id:'a',text:'Sistema Nervoso Central'}, {id:'b',text:'Tubo Digestivo (Estômago e Intestinos)'}, {id:'c',text:'Sistema Muscular'}], correctAnswers: ['b'] },
    { id: 305, difficulty: 'dificil', text: 'No princípio ALARA (As Low As Reasonably Achievable), qual é a sua aplicação prática na Imagiologia?', type: 'single', options: [{id:'a',text:'Dar sempre a dose máxima ao paciente para ter certeza do diagnóstico'}, {id:'b',text:'Ajustar a dose de radiação ao mínimo estritamente necessário para obter imagem de diagnóstico válida'}, {id:'c',text:'Não utilizar radiação ionizante sob nenhuma circunstância'}], correctAnswers: ['b'] },
    { id: 306, difficulty: 'facil', text: 'A Tomografia Computadorizada (TC) permite gerar imagens do corpo em cortes axiais através de:', type: 'single', options: [{id:'a',text:'Ultrassons acústicos'}, {id:'b',text:'Um tubo de Raio-X a rodar à volta do paciente'}, {id:'c',text:'Campos magnéticos e ondas de rádio'}], correctAnswers: ['b'] },
    { id: 307, difficulty: 'normal', text: 'A Ultrassonografia (Ecografia) tem a grande vantagem de:', type: 'single', options: [{id:'a',text:'Atravessar o osso com grande nitidez'}, {id:'b',text:'Ser isenta de radiação ionizante, o que a torna segura para grávidas e crianças'}, {id:'c',text:'Requerer injecção de material radioativo'}], correctAnswers: ['b'] },
    { id: 308, difficulty: 'dificil', text: 'O Dosímetro Pessoal de um técnico de radiologia deve ser usado:', type: 'single', options: [{id:'a',text:'Apenas dentro do avental de chumbo para proteger o medidor'}, {id:'b',text:'Por fora do avental de chumbo à altura do peito/colarinho, para medir a dose efetiva recebida pelo profissional'}, {id:'c',text:'Apenas durante a gravidez do técnico'}], correctAnswers: ['b'] },
    { id: 309, difficulty: 'normal', text: 'A Radiologia convencional de um Tórax foca-se em avaliar sobretudo:', type: 'multiple', options: [{id:'a',text:'A parênquima pulmonar e as vias aéreas'}, {id:'b',text:'O índice cardiotorácico e a silhueta cardíaca'}, {id:'c',text:'O detalhe microvascular do cérebro'}], correctAnswers: ['a','b'] },
    { id: 310, difficulty: 'facil', text: 'Um ambiente com símbolo do "Trevo Preto e Amarelo" significa presença de:', type: 'single', options: [{id:'a',text:'Risco Químico e inflamável'}, {id:'b',text:'Risco Biológico e infeccioso'}, {id:'c',text:'Risco Radiológico (Radiação ionizante)'}], correctAnswers: ['c'] },
    { id: 311, difficulty: 'dificil', text: 'Na obtenção da imagem radiográfica, o efeito Compton e o efeito Fotoelétrico são responsáveis, respetivamente, por:', type: 'single', options: [{id:'a',text:'Melhoria da imagem e perda da imagem'}, {id:'b',text:'Dispersão da radiação (redução do contraste e risco para o técnico) e absorção pelo paciente (produção do contraste)'}, {id:'c',text:'Apenas aquecimento da sala'}], correctAnswers: ['b'] },
    { id: 312, difficulty: 'normal', text: 'O uso de contraste iodado intravenoso na TAC requer precaução redobrada em doentes com:', type: 'single', options: [{id:'a',text:'Alergias severas ou Função Renal diminuída'}, {id:'b',text:'Apenas fraturas musculares'}, {id:'c',text:'Miopia'}], correctAnswers: ['a'] },
    { id: 313, difficulty: 'facil', text: 'Para a proteção da tiróide do paciente e do técnico durante procedimentos radiológicos, deve-se usar um:', type: 'single', options: [{id:'a',text:'Cachecol de lã'}, {id:'b',text:'Protetor de pescoço (colar) em chumbo'}, {id:'c',text:'Protetor de plástico'}], correctAnswers: ['b'] },
    { id: 314, difficulty: 'dificil', text: 'A Grelha Antidifusora na radiologia convencional tem a função primária de:', type: 'single', options: [{id:'a',text:'Proteger a maca de quebras'}, {id:'b',text:'Absorver a radiação dispersa antes que atinja a película, melhorando o contraste e nitidez'}, {id:'c',text:'Aumentar a dose absorvida no paciente'}], correctAnswers: ['b'] },
    { id: 315, difficulty: 'normal', text: 'Em relação à Ecografia Doppler, ela é ideal para estudar:', type: 'single', options: [{id:'a',text:'O fluxo e velocidade do sangue nas artérias e veias'}, {id:'b',text:'A estrutura óssea de micro-fraturas'}, {id:'c',text:'O ar nos pulmões'}], correctAnswers: ['a'] },
    { id: 316, difficulty: 'facil', text: 'Uma das grandes utilidades da Radiologia de intervenção e Hemodinâmica é a realização de:', type: 'single', options: [{id:'a',text:'Angioplastias e cateterismos guiados por fluoroscopia'}, {id:'b',text:'Massagens desportivas'}, {id:'c',text:'Aconselhamento psicológico'}], correctAnswers: ['a'] },
    { id: 317, difficulty: 'dificil', text: 'A Fluoroscopia caracteriza-se por fornecer imagens:', type: 'single', options: [{id:'a',text:'Dinâmicas em tempo real, úteis em estudos baritados ou angiográficos'}, {id:'b',text:'Apenas tridimensionais, em repouso absoluto'}, {id:'c',text:'Termográficas da pele'}], correctAnswers: ['a'] },
    { id: 318, difficulty: 'normal', text: 'Um cuidado essencial num departamento de TAC/Raios-X para mulheres em idade fértil é:', type: 'single', options: [{id:'a',text:'Questionar sempre a possibilidade de gravidez antes da exposição (Regra dos 10 dias)'}, {id:'b',text:'Recusar todas as mulheres com menos de 40 anos'}, {id:'c',text:'Ignorar a gravidez, pois os equipamentos novos não emitem raios'}], correctAnswers: ['a'] },
    { id: 319, difficulty: 'dificil', text: 'A técnica de Radiologia Convencional utiliza os parâmetros kV, mAs e Distância. O mAs (Miliampere-segundo) controla diretamente:', type: 'single', options: [{id:'a',text:'A energia e poder de penetração dos raios (qualidade)'}, {id:'b',text:'A quantidade (densidade/intensidade) da radiação produzida'}, {id:'c',text:'A temperatura da sala'}], correctAnswers: ['b'] },
    { id: 320, difficulty: 'facil', text: 'A ecocardiografia serve para analisar de forma não invasiva:', type: 'single', options: [{id:'a',text:'Apenas as costelas'}, {id:'b',text:'As válvulas, o miocárdio e a função do coração'}, {id:'c',text:'O intestino delgado'}], correctAnswers: ['b'] },
    { id: 321, difficulty: 'normal', text: 'Qual destas modalidades imagiológicas baseia-se num grande campo magnético (Tesla) em vez de radiação ionizante?', type: 'single', options: [{id:'a',text:'Tomografia Computadorizada'}, {id:'b',text:'Ressonância Magnética (RM)'}, {id:'c',text:'Mamografia'}], correctAnswers: ['b'] },
    { id: 322, difficulty: 'dificil', text: 'Na avaliação de Trauma Cranioencefálico, qual é o exame inicial de eleição devido à sua rapidez e alta sensibilidade para hemorragias agudas?', type: 'single', options: [{id:'a',text:'Ecografia craniana'}, {id:'b',text:'TC (Tomografia Computadorizada) sem contraste'}, {id:'c',text:'Ressonância Magnética com contraste'}], correctAnswers: ['b'] },
    { id: 323, difficulty: 'normal', text: 'As reações adversas ao contraste iodado podem ir de leves a severas, sendo a mais crítica:', type: 'single', options: [{id:'a',text:'Sabor metálico leve'}, {id:'b',text:'Choque Anafilático, requerendo intervenção imediata e suporte respiratório'}, {id:'c',text:'Aumento das unhas'}], correctAnswers: ['b'] },
    { id: 324, difficulty: 'facil', text: 'Num exame de ecografia pélvica, por que razão é geralmente pedido ao paciente para beber água (bexiga cheia)?', type: 'single', options: [{id:'a',text:'Para evitar a desidratação na sala de espera'}, {id:'b',text:'Porque a bexiga cheia atua como uma "janela acústica" facilitando a visualização dos órgãos pélvicos (útero/próstata)'}, {id:'c',text:'Para aumentar a pressão arterial'}], correctAnswers: ['b'] },
    { id: 325, difficulty: 'dificil', text: 'Em Hemodinâmica, a colocação de um "Stent" numa artéria coronária visa:', type: 'single', options: [{id:'a',text:'Reduzir a pressão do sangue artificialmente'}, {id:'b',text:'Manter o vaso aberto e revascularizar a área afetada por estenose/isquemia'}, {id:'c',text:'Servir de fio elétrico para pacemaker'}], correctAnswers: ['b'] }
];

const qFisioterapia = [
    { id: 401, difficulty: 'facil', text: 'Um dos grandes objetivos da fisioterapia após uma fratura imobilizada é:', type: 'single', options: [{id:'a',text:'Manter o membro engessado para sempre'}, {id:'b',text:'Recuperar a amplitude de movimento articular e reforçar a força muscular'}, {id:'c',text:'Administrar antibióticos'}], correctAnswers: ['b'] },
    { id: 402, difficulty: 'facil', text: 'A cinesioterapia baseia-se primariamente em:', type: 'single', options: [{id:'a',text:'Uso exclusivo de máquinas elétricas'}, {id:'b',text:'Exercícios e movimento corporal como terapia'}, {id:'c',text:'Fisioterapia em piscina apenas'}], correctAnswers: ['b'] },
    { id: 403, difficulty: 'normal', text: 'Na avaliação postural de um paciente, uma acentuação exagerada da curvatura dorsal denomina-se:', type: 'single', options: [{id:'a',text:'Lordose'}, {id:'b',text:'Cifose (Hipercifose)'}, {id:'c',text:'Escoliose'}], correctAnswers: ['b'] },
    { id: 404, difficulty: 'normal', text: 'A fisioterapia respiratória em pacientes com Doença Pulmonar Obstrutiva Crónica (DPOC) visa:', type: 'multiple', options: [{id:'a',text:'Desobstrução brônquica e melhoria da ventilação pulmonar'}, {id:'b',text:'Treino dos músculos respiratórios'}, {id:'c',text:'Agravar as resistências aéreas'}], correctAnswers: ['a','b'] },
    { id: 405, difficulty: 'dificil', text: 'A Escala de Ashworth Modificada (MAS) é amplamente utilizada em fisioterapia neurológica para avaliar:', type: 'single', options: [{id:'a',text:'A dor nociceptiva muscular'}, {id:'b',text:'O tónus muscular e grau de espasticidade'}, {id:'c',text:'A capacidade vital pulmonar'}], correctAnswers: ['b'] },
    { id: 406, difficulty: 'facil', text: 'No paciente com síndrome de imobilismo grave (acamado crónico), o fisioterapeuta atua ativamente para prevenir:', type: 'multiple', options: [{id:'a',text:'Úlceras de pressão e atrofia'}, {id:'b',text:'Trombose Venosa Profunda (TVP)'}, {id:'c',text:'Acidentes de viação'}], correctAnswers: ['a','b'] },
    { id: 407, difficulty: 'normal', text: 'Qual das seguintes afirmações sobre Diatermia por ondas curtas é verdadeira?', type: 'single', options: [{id:'a',text:'Aquece tecidos profundos e está contraindicada em pacientes com pacemakers ou implantes metálicos na zona'}, {id:'b',text:'Aplica frio intenso nas articulações'}, {id:'c',text:'É a técnica primária para tratar hemorragias ativas'}], correctAnswers: ['a'] },
    { id: 408, difficulty: 'dificil', text: 'Durante a reabilitação de uma amputação transfemoral, a principal contratura que a equipa de fisioterapia deve prevenir precocemente no coto é a de:', type: 'single', options: [{id:'a',text:'Extensão da anca'}, {id:'b',text:'Flexão e abdução da anca'}, {id:'c',text:'Rotação medial rígida'}], correctAnswers: ['b'] },
    { id: 409, difficulty: 'normal', text: 'No AVC isquémico, com hemiplegia de um dos lados do corpo, a reabilitação precoce é vital devido à:', type: 'single', options: [{id:'a',text:'Neuroplasticidade cerebral, que é maior nos primeiros meses'}, {id:'b',text:'Necessidade de fortalecer os músculos da perna não afetada apenas'}, {id:'c',text:'Falta de camas no hospital'}], correctAnswers: ['a'] },
    { id: 410, difficulty: 'facil', text: 'O uso de gelo (crioterapia) no pós-trauma agudo (ex: entorse no primeiro dia) serve essencialmente para:', type: 'single', options: [{id:'a',text:'Aumentar muito o inchaço'}, {id:'b',text:'Aliviar a dor e causar vasoconstrição para diminuir o edema/inflamação aguda'}, {id:'c',text:'Aumentar a inflamação de propósito'}], correctAnswers: ['b'] },
    { id: 411, difficulty: 'dificil', text: 'Na avaliação fisiátrica, o goniômetro é um instrumento utilizado rigorosamente para:', type: 'single', options: [{id:'a',text:'Avaliar a capacidade respiratória'}, {id:'b',text:'Medir a amplitude de movimento articular (ADM) em graus'}, {id:'c',text:'Medir a percentagem de massa gorda'}], correctAnswers: ['b'] },
    { id: 412, difficulty: 'normal', text: 'Uma órtese de tipo colete Milwaukee/Boston é geralmente prescrita para ajudar no tratamento não-operatório de:', type: 'single', options: [{id:'a',text:'Luxação da anca'}, {id:'b',text:'Escoliose idiopática na adolescência'}, {id:'c',text:'Artrose dos joelhos'}], correctAnswers: ['b'] },
    { id: 413, difficulty: 'facil', text: 'A massoterapia e drenagem linfática manual em membros edemaciados ajudam a:', type: 'single', options: [{id:'a',text:'Promover o fluxo dos líquidos linfáticos retidos e diminuir o inchaço'}, {id:'b',text:'Estripar a pele'}, {id:'c',text:'Aumentar a pressão do sangue arterial'}], correctAnswers: ['a'] },
    { id: 414, difficulty: 'dificil', text: 'Em cuidados intensivos pediátricos (neonatologia), um dos riscos do excesso prolongado de oxigénio (Hipóxia vs Hiperóxia) nos RN pré-termo é:', type: 'single', options: [{id:'a',text:'O desenvolvimento imediato de dentição'}, {id:'b',text:'Retinopatia da prematuridade ou Displasia Broncopulmonar'}, {id:'c',text:'O aumento da produção de cabelo'}], correctAnswers: ['b'] },
    { id: 415, difficulty: 'normal', text: 'Num paciente com lesão neurológica periférica (ex: paralisia facial de Bell), a fisioterapia frequentemente inclui:', type: 'multiple', options: [{id:'a',text:'Eletroestimulação facial controlada'}, {id:'b',text:'Exercícios de mímica e facilitação neuromuscular'}, {id:'c',text:'Radioterapia profunda no crânio'}], correctAnswers: ['a','b'] },
    { id: 416, difficulty: 'facil', text: 'Uma "Luxação" é uma lesão traumática onde:', type: 'single', options: [{id:'a',text:'O osso parte mas não rasga a pele'}, {id:'b',text:'Há uma perda completa do contacto entre as superfícies articulares dos ossos'}, {id:'c',text:'O músculo rasga um bocadinho (distensão)'}], correctAnswers: ['b'] },
    { id: 417, difficulty: 'dificil', text: 'O Reflexo de Babinski presente de forma positiva num adulto (extensão do hálux) é um sinal clássico de:', type: 'single', options: [{id:'a',text:'Normalidade muscular'}, {id:'b',text:'Lesão do neurónio motor superior (via piramidal)'}, {id:'c',text:'Lesão no nervo ciático (periférico)'}], correctAnswers: ['b'] },
    { id: 418, difficulty: 'normal', text: 'O treino proprioceptivo após uma entorse severa do tornozelo é essencial para:', type: 'single', options: [{id:'a',text:'Engordar a perna'}, {id:'b',text:'Restaurar o sentido de posição articular e equilíbrio, prevenindo recidivas'}, {id:'c',text:'Curar feridas na pele'}], correctAnswers: ['b'] },
    { id: 419, difficulty: 'facil', text: 'Na avaliação da marcha, o período em que ambos os pés estão em contacto com o chão simultaneamente denomina-se:', type: 'single', options: [{id:'a',text:'Apoio unipedal'}, {id:'b',text:'Fase de duplo apoio'}, {id:'c',text:'Fase de balanço puro'}], correctAnswers: ['b'] },
    { id: 420, difficulty: 'dificil', text: 'Para o controlo e diminuição da pressão intracraniana moderada num paciente politraumatizado cranioencefálico, a cabeceira da cama (banho no leito/fisioterapia) deve manter-se idealmente elevada a:', type: 'single', options: [{id:'a',text:'0 graus (plana)'}, {id:'b',text:'Cerca de 30 graus, alinhando a cabeça e pescoço para facilitar drenagem venosa'}, {id:'c',text:'90 graus exatos (sentado)'}], correctAnswers: ['b'] },
    { id: 421, difficulty: 'normal', text: 'Na asma brônquica crônica, o quadro de dispneia ocorre predominantemente devido a:', type: 'single', options: [{id:'a',text:'Pneumotórax'}, {id:'b',text:'Broncoespasmo reversível, inflamação e hipersecreção de muco'}, {id:'c',text:'Embolia pulmonar massiva'}], correctAnswers: ['b'] },
    { id: 422, difficulty: 'facil', text: 'A Órtese ou Prótese: Qual substitui a ausência de um membro inteiro ou parcial?', type: 'single', options: [{id:'a',text:'Órtese'}, {id:'b',text:'Prótese'}, {id:'c',text:'Nenhuma delas'}], correctAnswers: ['b'] },
    { id: 423, difficulty: 'dificil', text: 'A Escoliose verdadeira é uma deformidade da coluna vertebral caracterizada por ser:', type: 'single', options: [{id:'a',text:'Exclusivamente de origem inflamatória'}, {id:'b',text:'Uma curva lateral da coluna em desvio rígido, obrigatoriamente associada a rotação vertebral tridimensional'}, {id:'c',text:'Curva anteroposterior na lombar'}], correctAnswers: ['b'] },
    { id: 424, difficulty: 'normal', text: 'O Suporte Avançado de Vida num adulto em Fibrilação Ventricular (FV) prioriza:', type: 'single', options: [{id:'a',text:'Massagem cardíaca e Desfibrilhação Elétrica precoce'}, {id:'b',text:'Apenas aplicar muito oxigénio pelas vias nasais'}, {id:'c',text:'Virar o doente de barriga para baixo'}], correctAnswers: ['a'] },
    { id: 425, difficulty: 'facil', text: 'Um dos fatores de risco maiores para as doenças cardiovasculares obstrutivas em programas de reabilitação é:', type: 'multiple', options: [{id:'a',text:'Hipertensão Arterial severa e não controlada'}, {id:'b',text:'Tabagismo e Sedentarismo extremo'}, {id:'c',text:'Praticar desporto moderadamente'}, {id:'d',text:'Comer fruta'}], correctAnswers: ['a','b'] }
];

// O Módulo "Misto" agrupa todas. Os Módulos Específicos aglomeram a sua área com Gerais
// Com exatamente as perguntas que existem, garantimos ZERO "Variantes".
// Se pedirem 50, mas o grupo daquela dificuldade só tiver 20, ele mostrará APENAS as 20 verdadeiras. Sem encher.
function getModuleData(moduleId, difficulty) {
    let pool = [];
    
    // Obter array
    if (moduleId === 'analises') pool = [...qAnalises, ...qGerais];
    else if (moduleId === 'farmacia') pool = [...qFarmacia, ...qGerais];
    else if (moduleId === 'radiologia') pool = [...qRadiologia, ...qGerais];
    else if (moduleId === 'fisioterapia') pool = [...qFisioterapia, ...qGerais];
    else if (moduleId === 'gerais') pool = [...qGerais];
    else if (moduleId === 'misto') pool = [...qAnalises, ...qFarmacia, ...qRadiologia, ...qFisioterapia, ...qGerais];

    // Filtrar pela dificuldade
    let filtered = pool.filter(q => q.difficulty === difficulty);
    
    // Se a filtragem for muito pequena e o utilizador quiser mais perguntas, em vez de inventar, limitamos o teste ao que existe
    return filtered.sort(() => Math.random() - 0.5); // Apenas baralhar e entregar
}
