const questions = [
    // --- DIVISÃO POLÍTICO-ADMINISTRATIVA DE ANGOLA (1-10) ---
    { id: 1, text: 'De acordo com a proposta de Nova Divisão Político-Administrativa de Angola, qual é um dos objetivos principais?', type: 'single', options: [{ id: 'a', text: 'Centralizar todo o poder em Luanda' }, { id: 'b', text: 'Aproximar os serviços públicos às populações' }, { id: 'c', text: 'Reduzir o número de municípios no país' }, { id: 'd', text: 'Privatizar os hospitais municipais' }], correctAnswers: ['b'] },
    { id: 2, text: 'A nova Divisão Político-Administrativa pode impactar o sector da saúde através da:', type: 'multiple', options: [{ id: 'a', text: 'Criação de novos cargos autárquicos em Luanda apenas' }, { id: 'b', text: 'Melhoria na distribuição e gestão local de recursos' }, { id: 'c', text: 'Facilitação no acompanhamento de indicadores de saúde municipais' }, { id: 'd', text: 'Redução total do orçamento de estado para saúde' }], correctAnswers: ['b', 'c'] },
    { id: 3, text: 'Quantas províncias Angola passa a ter (ou projeta ter) com a nova divisão político-administrativa recente (2024)?', type: 'single', options: [{ id: 'a', text: '18' }, { id: 'b', text: '20' }, { id: 'c', text: '21' }, { id: 'd', text: '24' }], correctAnswers: ['c'] },
    { id: 4, text: 'Qual é o benefício de ter mais municípios no que toca aos serviços de saúde?', type: 'single', options: [{ id: 'a', text: 'Diminui o controlo das epidemias' }, { id: 'b', text: 'Aumenta a distância para os centros médicos' }, { id: 'c', text: 'Permite uma planificação orçamental mais ajustada às realidades locais' }, { id: 'd', text: 'Obriga os cidadãos a viajarem mais para obter tratamento' }], correctAnswers: ['c'] },
    { id: 5, text: 'A gestão dos serviços de saúde ao nível de um município é gerida por:', type: 'single', options: [{ id: 'a', text: 'Direção Nacional de Saúde Pública' }, { id: 'b', text: 'Direção Municipal de Saúde' }, { id: 'c', text: 'Ministério das Finanças' }, { id: 'd', text: 'Governo Provincial exclusivamente' }], correctAnswers: ['b'] },
    { id: 6, text: 'Como a criação de novas províncias afeta a rede sanitária nacional?', type: 'multiple', options: [{ id: 'a', text: 'Exige a criação de novos hospitais provinciais' }, { id: 'b', text: 'Descentraliza a resposta a emergências' }, { id: 'c', text: 'Diminui o número de enfermeiros em Angola' }, { id: 'd', text: 'Aumenta a necessidade de mapas epidemiológicos locais' }], correctAnswers: ['a', 'b', 'd'] },
    { id: 7, text: 'Na nova organização, as comunas e distritos urbanos continuam a ter relevância para os cuidados primários de saúde?', type: 'single', options: [{ id: 'a', text: 'Não, todos os postos de saúde serão encerrados' }, { id: 'b', text: 'Sim, são fundamentais para o primeiro ponto de contacto (cuidados primários)' }, { id: 'c', text: 'Apenas para campanhas eleitorais' }, { id: 'd', text: 'Não, tudo será tratado apenas em hospitais provinciais' }], correctAnswers: ['b'] },
    { id: 8, text: 'Qual o papel do cidadão na nova Divisão Administrativa em termos de saúde pública?', type: 'multiple', options: [{ id: 'a', text: 'Participar na identificação de problemas locais' }, { id: 'b', text: 'Não intervir, deixando tudo para o governo' }, { id: 'c', text: 'Contribuir para a fiscalização da gestão dos hospitais municipais' }, { id: 'd', text: 'Garantir que a capital tenha os melhores médicos' }], correctAnswers: ['a', 'c'] },
    { id: 9, text: 'A descentralização administrativa em Angola visa:', type: 'single', options: [{ id: 'a', text: 'Delegar competências e recursos para os governos locais' }, { id: 'b', text: 'Tirar o poder dos hospitais' }, { id: 'c', text: 'Acabar com o Ministério da Saúde' }, { id: 'd', text: 'Concentrar médicos apenas no litoral' }], correctAnswers: ['a'] },
    { id: 10, text: 'Os Administradores Municipais têm responsabilidade sobre:', type: 'multiple', options: [{ id: 'a', text: 'Hospitais Nacionais de referência' }, { id: 'b', text: 'Centros e Postos de Saúde da sua área' }, { id: 'c', text: 'Campanhas locais de vacinação e saneamento' }, { id: 'd', text: 'Produção de vacinas' }], correctAnswers: ['b', 'c'] },

    // --- CENSO POPULACIONAL 2024 (11-20) ---
    { id: 11, text: 'Qual o principal objetivo do Censo Geral da População e Habitação de 2024?', type: 'single', options: [{ id: 'a', text: 'Saber quantos estrangeiros vivem no país para os expulsar' }, { id: 'b', text: 'Contar a população e habitação para planificar o desenvolvimento do país' }, { id: 'c', text: 'Eleger o novo presidente da república' }, { id: 'd', text: 'Recrutar profissionais de saúde' }], correctAnswers: ['b'] },
    { id: 12, text: 'Por que o Censo 2024 é crítico para o Ministério da Saúde?', type: 'multiple', options: [{ id: 'a', text: 'Permite saber onde há mais concentração populacional' }, { id: 'b', text: 'Ajuda a calcular as taxas de mortalidade e natalidade de forma precisa' }, { id: 'c', text: 'Ajuda a definir quem será médico ou enfermeiro' }, { id: 'd', text: 'Orienta a distribuição de vacinas e medicamentos' }], correctAnswers: ['a', 'b', 'd'] },
    { id: 13, text: 'O Censo recolhe indicadores demográficos fundamentais. Quais destes são exemplos?', type: 'multiple', options: [{ id: 'a', text: 'Idade e sexo da população' }, { id: 'b', text: 'Marca do carro que a família possui' }, { id: 'c', text: 'Taxa de literacia e acesso a água' }, { id: 'd', text: 'Partidos políticos da preferência' }], correctAnswers: ['a', 'c'] },
    { id: 14, text: 'Com os dados censitários de 2024, o governo poderá melhorar:', type: 'single', options: [{ id: 'a', text: 'A meteorologia nacional' }, { id: 'b', text: 'As políticas públicas, como a expansão da rede hospitalar' }, { id: 'c', text: 'A qualidade do entretenimento na TV' }, { id: 'd', text: 'A constituição da república' }], correctAnswers: ['b'] },
    { id: 15, text: 'Qual é o intervalo normal de tempo entre a realização de Censos Gerais num país (por norma internacional)?', type: 'single', options: [{ id: 'a', text: '1 ano' }, { id: 'b', text: '5 anos' }, { id: 'c', text: '10 anos' }, { id: 'd', text: '20 anos' }], correctAnswers: ['c'] },
    { id: 16, text: 'Um indicador crucial obtido indiretamente pelo censo e vital para a pediatria é:', type: 'single', options: [{ id: 'a', text: 'Taxa de alfabetização de adultos' }, { id: 'b', text: 'Proporção de crianças de 0 a 5 anos na população' }, { id: 'c', text: 'Número de estradas asfaltadas' }, { id: 'd', text: 'Quantidade de shoppings na cidade' }], correctAnswers: ['b'] },
    { id: 17, text: 'O censo ajuda na identificação de zonas de risco para a saúde pública (ex: cólera) através do mapeamento de:', type: 'multiple', options: [{ id: 'a', text: 'Habitações sem acesso a água canalizada' }, { id: 'b', text: 'Taxas de desemprego' }, { id: 'c', text: 'Famílias sem saneamento básico' }, { id: 'd', text: 'Número de pessoas por habitação (superlotação)' }], correctAnswers: ['a', 'c', 'd'] },
    { id: 18, text: 'Quem é o órgão responsável pela execução do Censo em Angola?', type: 'single', options: [{ id: 'a', text: 'Ministério da Saúde' }, { id: 'b', text: 'INE (Instituto Nacional de Estatística)' }, { id: 'c', text: 'Ministério do Interior' }, { id: 'd', text: 'Polícia Nacional' }], correctAnswers: ['b'] },
    { id: 19, text: 'Como o crescimento populacional afeta a distribuição de recursos do MINSA?', type: 'single', options: [{ id: 'a', text: 'Não afeta, os recursos são estáticos' }, { id: 'b', text: 'Exige reajustes constantes no orçamento para garantir rácio cama/paciente adequados' }, { id: 'c', text: 'Significa que menos hospitais são precisos' }, { id: 'd', text: 'Afeta apenas a província de Luanda' }], correctAnswers: ['b'] },
    { id: 20, text: 'Os dados do Censo 2024 são sigilosos do ponto de vista individual?', type: 'single', options: [{ id: 'a', text: 'Não, qualquer pessoa pode ver as respostas do vizinho' }, { id: 'b', text: 'Sim, são protegidos pelo segredo estatístico e usados apenas de forma agregada' }, { id: 'c', text: 'Parcialmente, apenas os dados de saúde são públicos' }, { id: 'd', text: 'Não há qualquer lei de proteção' }], correctAnswers: ['b'] },

    // --- IIMS (Inquérito de Indicadores Múltiplos e de Saúde) (21-30) ---
    { id: 21, text: 'O que significa IIMS?', type: 'single', options: [{ id: 'a', text: 'Inquérito de Identificação de Médicos de Saúde' }, { id: 'b', text: 'Inquérito de Indicadores Múltiplos e de Saúde' }, { id: 'c', text: 'Instituto Internacional de Medicina Saudável' }, { id: 'd', text: 'Inquérito Interno do Ministério da Saúde' }], correctAnswers: ['b'] },
    { id: 22, text: 'Qual é o principal foco do IIMS no que toca à saúde materno-infantil?', type: 'multiple', options: [{ id: 'a', text: 'Taxa de mortalidade infantil' }, { id: 'b', text: 'Prevalência de desnutrição (peso e altura)' }, { id: 'c', text: 'Taxas de vacinação (Programa Alargado de Vacinação)' }, { id: 'd', text: 'Acidentes de viação de adultos' }], correctAnswers: ['a', 'b', 'c'] },
    { id: 23, text: 'O IIMS mede a taxa de mortalidade materna. Isto serve para:', type: 'single', options: [{ id: 'a', text: 'Saber a idade média das mães' }, { id: 'b', text: 'Avaliar a eficácia da assistência ao parto e pré-natal' }, { id: 'c', text: 'Aumentar os impostos' }, { id: 'd', text: 'Mudar o calendário escolar' }], correctAnswers: ['b'] },
    { id: 24, text: 'Na avaliação nutricional infantil do IIMS, avalia-se frequentemente:', type: 'multiple', options: [{ id: 'a', text: 'O raquitismo e atraso de crescimento' }, { id: 'b', text: 'As taxas de aleitamento materno exclusivo' }, { id: 'c', text: 'A ingestão de refrigerantes por recém-nascidos' }, { id: 'd', text: 'A prevalência de anemia' }], correctAnswers: ['a', 'b', 'd'] },
    { id: 25, text: 'O IIMS ajuda a determinar a cobertura de uso de redes mosquiteiras tratadas para o combate a qual doença?', type: 'single', options: [{ id: 'a', text: 'Tuberculose' }, { id: 'b', text: 'VIH/SIDA' }, { id: 'c', text: 'Malária' }, { id: 'd', text: 'Febre Amarela' }], correctAnswers: ['c'] },
    { id: 26, text: 'Qual a utilidade do IIMS no planeamento sanitário?', type: 'single', options: [{ id: 'a', text: 'Alocar recursos de forma mais equitativa onde os indicadores de saúde são piores' }, { id: 'b', text: 'Fechar unidades sanitárias nas províncias do sul' }, { id: 'c', text: 'Ignorar as províncias com piores resultados' }, { id: 'd', text: 'Determinar apenas o salário dos enfermeiros' }], correctAnswers: ['a'] },
    { id: 27, text: 'Em relação ao VIH/SIDA, o IIMS frequentemente avalia:', type: 'multiple', options: [{ id: 'a', text: 'O nível de conhecimento sobre prevenção' }, { id: 'b', text: 'Comportamentos sexuais de risco' }, { id: 'c', text: 'O número de casos curados definitivamente' }, { id: 'd', text: 'A taxa de realização do teste de VIH' }], correctAnswers: ['a', 'b', 'd'] },
    { id: 28, text: 'O que é a TMI (Taxa de Mortalidade Infantil) avaliada no IIMS?', type: 'single', options: [{ id: 'a', text: 'Óbitos de adolescentes' }, { id: 'b', text: 'Óbitos de crianças menores de 1 ano por cada 1.000 nados-vivos' }, { id: 'c', text: 'Óbitos gerais na população' }, { id: 'd', text: 'Mortes por acidentes' }], correctAnswers: ['b'] },
    { id: 29, text: 'Os dados do IIMS 2023-2024 mostram resultados essenciais para o alcance dos:', type: 'single', options: [{ id: 'a', text: 'Objetivos de Desenvolvimento Sustentável (ODS)' }, { id: 'b', text: 'Jogos Olímpicos' }, { id: 'c', text: 'Censos Eleitorais' }, { id: 'd', text: 'Relatórios do Banco Mundial para agricultura' }], correctAnswers: ['a'] },
    { id: 30, text: 'Para reduzir os indicadores negativos materno-infantis, o técnico de saúde deve:', type: 'multiple', options: [{ id: 'a', text: 'Apostar na educação para a saúde' }, { id: 'b', text: 'Ignorar as estatísticas' }, { id: 'c', text: 'Garantir o seguimento da mulher grávida' }, { id: 'd', text: 'Promover o planeamento familiar' }], correctAnswers: ['a', 'c', 'd'] },

    // --- INTELIGÊNCIA ARTIFICIAL (IA) (31-40) ---
    { id: 31, text: 'O que é a Inteligência Artificial (IA) aplicada à saúde?', type: 'single', options: [{ id: 'a', text: 'O uso de robôs físicos para limpar o hospital' }, { id: 'b', text: 'Sistemas informáticos analisarem dados e apoiarem no diagnóstico e decisão médica' }, { id: 'c', text: 'Uma máquina de raio-x analógica' }, { id: 'd', text: 'A substituição de todos os médicos por computadores' }], correctAnswers: ['b'] },
    { id: 32, text: 'Quais as aplicações comuns da IA na saúde pública moderna?', type: 'multiple', options: [{ id: 'a', text: 'Diagnóstico assistido por análise de imagens' }, { id: 'b', text: 'Previsão de surtos epidémicos' }, { id: 'c', text: 'Telemedicina inteligente e Chatbots' }, { id: 'd', text: 'Fazer cirurgias sem qualquer supervisão humana' }], correctAnswers: ['a', 'b', 'c'] },
    { id: 33, text: 'Em relação aos riscos e ética da IA na saúde, um grande desafio é:', type: 'single', options: [{ id: 'a', text: 'Os computadores serem muito baratos' }, { id: 'b', text: 'A proteção de dados e privacidade dos pacientes' }, { id: 'c', text: 'A falta de eletricidade nas cidades' }, { id: 'd', text: 'Os médicos deixarem de falar' }], correctAnswers: ['b'] },
    { id: 34, text: 'O que significa privacidade e proteção de dados quando se usa IA?', type: 'single', options: [{ id: 'a', text: 'Partilhar exames no Facebook' }, { id: 'b', text: 'Garantir que os dados clínicos não sejam usados indevidamente pelos algoritmos' }, { id: 'c', text: 'Apagar todos os dados após um dia' }, { id: 'd', text: 'Imprimir relatórios médicos' }], correctAnswers: ['b'] },
    { id: 35, text: 'A IA pode ajudar na triagem de urgências através de:', type: 'multiple', options: [{ id: 'a', text: 'Algoritmos preditivos de risco' }, { id: 'b', text: 'Reconhecimento de voz e processamento de linguagem' }, { id: 'c', text: 'Negando atendimento aos pacientes com pulseira verde' }, { id: 'd', text: 'Priorizando pacientes automaticamente por gravidade' }], correctAnswers: ['a', 'b', 'd'] },
    { id: 36, text: 'Um benefício económico do uso de IA num hospital público é:', type: 'single', options: [{ id: 'a', text: 'Despedir enfermeiros' }, { id: 'b', text: 'Reduzir custos operacionais, otimizando agendamentos e recursos' }, { id: 'c', text: 'Fazer os pacientes pagarem mais pelos exames' }, { id: 'd', text: 'Criar novas taxas informáticas' }], correctAnswers: ['b'] },
    { id: 37, text: 'Ao usar software de IA para auxílio no diagnóstico, a decisão final:', type: 'single', options: [{ id: 'a', text: 'Cabe sempre ao algoritmo' }, { id: 'b', text: 'Deve ser sempre do profissional de saúde (médico/técnico)' }, { id: 'c', text: 'Cabe ao diretor do hospital' }, { id: 'd', text: 'É dispensável' }], correctAnswers: ['b'] },
    { id: 38, text: 'Os riscos associados à IA no sector público incluem:', type: 'multiple', options: [{ id: 'a', text: 'Viés e discriminação (algoritmos mal treinados)' }, { id: 'b', text: 'Aumento de vulnerabilidade a ataques informáticos' }, { id: 'c', text: 'Melhoria na velocidade do diagnóstico' }, { id: 'd', text: 'Falta de clareza na responsabilidade jurídica em caso de erro' }], correctAnswers: ['a', 'b', 'd'] },
    { id: 39, text: 'O que se entende por "Big Data" na saúde?', type: 'single', options: [{ id: 'a', text: 'Um ficheiro Excel simples' }, { id: 'b', text: 'Grandes volumes de dados de saúde analisáveis para encontrar padrões e tendências' }, { id: 'c', text: 'O disco duro principal do Ministério' }, { id: 'd', text: 'Dados apenas de grandes hospitais privados' }], correctAnswers: ['b'] },
    { id: 40, text: 'A ética da IA na saúde exige:', type: 'multiple', options: [{ id: 'a', text: 'Transparência nos algoritmos utilizados' }, { id: 'b', text: 'Equidade no tratamento' }, { id: 'c', text: 'Uso de dados para publicidade' }, { id: 'd', text: 'Responsabilidade humana pelas decisões' }], correctAnswers: ['a', 'b', 'd'] },

    // --- Pauta Deontológica, Ética e Cultura Geral (41-50) ---
    { id: 41, text: 'A Pauta Deontológica da Função Pública estipula que o funcionário deve agir com:', type: 'single', options: [{ id: 'a', text: 'Arogança e superioridade' }, { id: 'b', text: 'Parcialidade' }, { id: 'c', text: 'Probidade, Zelo, Imparcialidade e Isenção' }, { id: 'd', text: 'Foco no interesse pessoal' }], correctAnswers: ['c'] },
    { id: 42, text: 'No atendimento a um doente, o respeito pelo sigilo profissional é:', type: 'single', options: [{ id: 'a', text: 'Opcional' }, { id: 'b', text: 'Obrigatório e um dever ético, salvo situações previstas na lei' }, { id: 'c', text: 'Aplicável apenas a figuras públicas' }, { id: 'd', text: 'Um mito' }], correctAnswers: ['b'] },
    { id: 43, text: 'O que caracteriza uma Organização da Administração Pública no Sector da Saúde?', type: 'multiple', options: [{ id: 'a', text: 'Procurar o lucro máximo' }, { id: 'b', text: 'Orientar-se para o interesse público e bem-estar do cidadão' }, { id: 'c', text: 'Obedecer a uma estrutura hierárquica' }, { id: 'd', text: 'Prestar serviço público de qualidade' }], correctAnswers: ['b', 'c', 'd'] },
    { id: 44, text: 'Se um funcionário público presenciar uma infração disciplinar grave de um colega, o seu dever é:', type: 'single', options: [{ id: 'a', text: 'Ignorar para evitar problemas' }, { id: 'b', text: 'Participar o facto aos seus superiores hierárquicos' }, { id: 'c', text: 'Espalhar boatos no serviço' }, { id: 'd', text: 'Tirar fotografias para a internet' }], correctAnswers: ['b'] },
    { id: 45, text: 'Quais são princípios centrais da Bioética na Saúde?', type: 'multiple', options: [{ id: 'a', text: 'Princípio da Beneficência' }, { id: 'b', text: 'Princípio da Autonomia do Paciente' }, { id: 'c', text: 'Princípio da Maleficência (Fazer o mal intencionalmente)' }, { id: 'd', text: 'Princípio da Justiça (Equidade)' }], correctAnswers: ['a', 'b', 'd'] },
    { id: 46, text: 'Um funcionário público pode aceitar presentes valiosos em troca de prioridade no atendimento?', type: 'single', options: [{ id: 'a', text: 'Sim, se o salário for baixo' }, { id: 'b', text: 'Não, constitui corrupção e violação da probidade' }, { id: 'c', text: 'Apenas na época festiva' }, { id: 'd', text: 'Sim, se ninguém descobrir' }], correctAnswers: ['b'] },
    { id: 47, text: 'Quando a vontade do paciente entra em conflito com o tratamento essencial para a sua vida, qual conflito ético está em causa?', type: 'single', options: [{ id: 'a', text: 'Princípio da Eficiência' }, { id: 'b', text: 'Autonomia vs Beneficência' }, { id: 'c', text: 'Gestão Financeira' }, { id: 'd', text: 'Divisão Político-Administrativa' }], correctAnswers: ['b'] },
    { id: 48, text: 'O Código de Ética Profissional serve primariamente para:', type: 'multiple', options: [{ id: 'a', text: 'Garantir o respeito pelos direitos humanos dos utentes' }, { id: 'b', text: 'Proteger a imagem e a dignidade da profissão' }, { id: 'c', text: 'Permitir faltas injustificadas' }, { id: 'd', text: 'Orientar a conduta técnica e moral dos profissionais' }], correctAnswers: ['a', 'b', 'd'] },
    { id: 49, text: 'No contexto de Cultura Geral da Saúde, qual evento provocou mudanças globais nos sistemas de biossegurança recentemente?', type: 'single', options: [{ id: 'a', text: 'Poliomielite' }, { id: 'b', text: 'Pandemia COVID-19' }, { id: 'c', text: 'Gripe Espanhola' }, { id: 'd', text: 'VIH/SIDA' }], correctAnswers: ['b'] },
    { id: 50, text: 'O que significa o Princípio da Imparcialidade na Administração Pública?', type: 'single', options: [{ id: 'a', text: 'Tratar todos os cidadãos de forma igualitária, sem discriminação' }, { id: 'b', text: 'Dar preferência a familiares' }, { id: 'c', text: 'Atender primeiro quem tem maior poder aquisitivo' }, { id: 'd', text: 'Privilegiar os utentes da mesma filiação partidária' }], correctAnswers: ['a'] }
];
